### ISSUE TITLE
how about add a the prefix of `linuxbrew/.linuxbrew` as a package?

### ISSUE THREAD

**Issue by specter119** [Homebrew/linuxbrew-core#11969]
I can't tell if a software will work without the prefix `linuxbrew/.linuxbrew` before I install it, since a lot of packages have bottle now.
For example, a lot of packages build with `rust`, like `fd`, will not work without the prefix `linuxbrew/.linuxbrew`. Besides, `brew desc fd` returns blank.
Therefore, how about change the prefix of `linuxbrew/.linuxbrew` as a package, and add to the packages like `fd` as dependency?

because, this specific prefix real act like a dependency, I know it may bring a huge incompatibility, but this is just my suggestion.

**Comment by iMichka** [comment]
`brew desc fd` returns: `fd: Simple, fast and user-friendly alternative to find`

Your issue is a little unclear. Do you mean you would want to know what will be poured from a bottle, and what will be built from source?

If you look at the bottle block, you will stuff like `cellar :any_skip_relocation`, `cellar :any`, or just nothing, which gives you a hint of what will happen. We do not display that information in `brew info`. I am not sure this is something we want to display right now.

Here is also our standard response:

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like util-linux. If it's an option for you, you could open a ticket with your information systems department to ask that they create a linuxbrew role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

http://docs.brew.sh/Installation.html#alternative-installs
http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by specter119** [comment]
thanks @iMichka , I get solutions from your words.
