### ISSUE TITLE
moarvm: error compiling "recompile with -fPIC"

### ISSUE THREAD

**Issue by ntysdd** [Homebrew/linuxbrew-core#12087]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
installing moarvm
`brew install moarvm`

- What happened (include command output)
compiling error

- What you expected to happen
no error
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install moarvm`

https://gist.github.com/ntysdd/7e18df8c982ef34375083a2dd416dfa2

**Comment by iMichka** [comment]
We probably just need to add `ENV.append_to_cflags "-fPIC" unless OS.mac?` to the formula. Could you try this out?

**Comment by ntysdd** [comment]
> We probably just need to add `ENV.append_to_cflags "-fPIC" unless OS.mac?` to the formula. Could you try this out?

Want me to test it?

How to do it then?

**Comment by iMichka** [comment]
Run `brew edit moarvm`. Or edit /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/moarvm.rb.

Add `ENV.append_to_cflags "-fPIC" unless OS.mac?` somewhere at the top of the `def install` method. Save and try again.

Once you are done, run `brew update-reset` to nuke you changes, so that homebrew is in a clean state again.

**Comment by ntysdd** [comment]
OK, I will try it.

**Comment by ntysdd** [comment]
@iMichka I still get similar errors.
https://gist.github.com/ntysdd/4140c2b2e818c312b6edee48c50a1825

**Comment by iMichka** [comment]
Tested myself, I can't get this to build. I think you should open a bug upstream to get some help from the developers: https://github.com/MoarVM/MoarVM

**Comment by atweiden** [comment]
@ntysdd,

I authored the MoarVM package for Homebrew on MacOS. If I may I'd like to offer you some advice.

Instead of attempting to troubleshoot build issues on esoteric package managers, you should switch to a Linux distribution like Void, Alpine, Gentoo or Arch where the native package manager is excellent. In addition to these distros having a better user experience for packagers, if you do encounter any issues on these distros, you're more likely to receive help.

If you're interested, I've written an installer for [Void](https://github.com/atweiden/voidvault) and [Arch](https://github.com/atweiden/archvault) which you are welcome to try out.

**Comment by ntysdd** [comment]
OK.

**Comment by iMichka** [comment]
> Instead of attempting to troubleshoot build issues on esoteric package managers

We do have a lot of users, and more than 2000 packages that work correctly. Of course you can not compare that to debian or any other distro, but still we are not a small weekend-project anymore.

> you're more likely to receive help

Other distro bug-trackers are full of open bugs that have never been solved. Some are 10 years old. The situation is the same here. It depends a lot on finding somebody that can fix the bug. I bet I can fix this bug. But that would mean sitting down a few hours and dig through the code. And I do not have the time right now (and probably will never have). It is up to the community (somebody interested in fixing this) to find a solution.

I propose to close this issue as right now nobody will work on this. The issue has been open for 25 days upstream. Looks like they have as much time as I have :) Anybody can submit a pull request to get this fixed.
