### ISSUE TITLE
Formulae `depends_on`/`uses_from_macos` "python@2"

### ISSUE THREAD

**Issue by issyl0** [Homebrew/linuxbrew-core#17914]
The Python 2 EOL is [fast approaching](https://pythonclock.org/). There's ongoing work in https://github.com/Homebrew/homebrew-core/issues/47050 to track the macOS repo's response. That work will get here via merges.

As of 2019-12-06, in Homebrew/linuxbrew-core:

```
$ ack "uses_from_macos \"python@2" | wc -l
21
 
$ ack "depends_on \"python@2" | wc -l
93
```

for a total of **114 formulae**, and in Homebrew/homebrew-core:

```
$ ack "uses_from_macos \"python@2" | wc -l
6

$ ack "depends_on \"python@2" | wc -l
51
```

for a total of **57 formulae with explicitly declared Python dependencies**. But macOS ships with Python 2 by default. (Which doesn't really help us. I've not got the hang of `brew uses` quite yet. But this is a good starter!)

That's a large difference on the `uses_from_macos` side of things. We should fix that up too.

----

To track the formulae that we should worry about - that is, the ones with a dependency on Python 2 not tracked in the linked Homebrew/homebrew-core issue - here's an alphabetically sorted, de-duplicated list:

- [x] ansible https://github.com/Homebrew/linuxbrew-core/pull/17940
- [ ] asciidoc https://github.com/Homebrew/homebrew-core/pull/47602
- [x] bear https://github.com/Homebrew/linuxbrew-core/pull/17941
- [ ] bedtools
- [x] ~~cassandra~~ https://github.com/Homebrew/linuxbrew-core/pull/17942
- [ ] chapel
- [ ] cppcheck
- [ ] czmq
- [ ] deno
- [ ] emscripten
- [ ] flawfinder
- [ ] git-archive-all
- [ ] gpgme
- [x] gsettings-desktop-schemas
- [ ] htop
- [ ] ibex
- [ ] iotop
- [ ] jailkit
- [ ] joplin
- [ ] kcov
- [ ] kibana
- [ ] ldns
- [ ] ledger #17943
- [ ] libgraphqlparser
- [ ] libming
- [ ] libpqxx
- [ ] libprelude
- [ ] libpsl
- [ ] libsoup
- [ ] libssh
- [ ] libstfl
- [ ] libtcod
- [ ] llvm
- [ ] llvm@6
- [ ] llvm@7
- [ ] llvm@8
- [ ] lv2
- [ ] mono
- [x] mpv https://github.com/Homebrew/linuxbrew-core/pull/17938
- [ ] nanomsgxx
- [ ] neovim
- [ ] ninja
- [ ] pyenv
- [ ] qt
- [ ] quex
- [ ] rethinkdb
- [x] rust
- [ ] scons
- [ ] shadowsocks-libev
- [ ] spades
- [ ] stgit
- [ ] subversion
- [ ] sync_gateway
- [ ] wabt
- [ ] zeek
- [ ] zpython

----

**Comment by iMichka** [comment]
Looks like you missed `node@10` for example.

**Comment by issyl0** [comment]
Ah, `node@10` was mentioned in the upstream issue.

**Comment by dawidd6** [comment]
Are we bumping the revision for those formulae that we modify to drop the python2 dependency?

**Comment by iMichka** [comment]
I finished the cleanup in homebrew-core.

On mac, we have:
30 formulae have uses_from_macos "python@2"
12 Do not support Python3 (the others, I do not know ...)

I will start annotating the remaining formulae that do not support Python3 on mac, so that we know for sure that we can not migrate them. I will then also try to migrate some more to Python3.

Meanwhile, we should add uses_from_macos "python@2" or migrate formulae to Python 3 in linuxbrew-core. The list above needs to be updated.

**Comment by woopla** [comment]
Seems that `gsettings-desktop-schemas` actually depends on Python **3** (look [here](https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/blob/master/build-aux/meson/post-install.py), so the formula file should just drop the dependency on Python 2. Can't install GTK+ 3 on Linux otherwise :crying_cat_face:

**Comment by issyl0** [comment]
@woopla Thanks for the note! It did work with Python 3. If you `brew update` you'll be able to install it.

**Comment by woopla** [comment]
Thanks for the quick fix @issyl0 !

**Comment by tseemann** [comment]
@issy i think you can :heavy_check_mark: spades now

**Comment by issyl0** [comment]
Yeah, I really need to regenerate this list!

**Comment by chrmoritz** [comment]
Hi, just some idea of mine, but do you have already thought about trying to use `pypy` instead of `python@2` for formulae which still depend on it / `uses_from_macos "python@2"`, but don't work with Python 3? It should be at least sufficient for formulae where `python@2` is just a simple build dependency (like `v8`, `deno`, ...) and [PyPy2.7 will be supported 'as long as PyPy itself is around'.](https://pypy.readthedocs.io/en/latest/faq.html#how-long-will-pypy-support-python2).

In my test I was able to build `deno` just fine using only `pypy` inside the `homebrew/brew` docker container with this patch https://github.com/chrmoritz/linuxbrew-core/commit/349e9b207db148f97fd882b36a29ac32f4eef665 (after [upgrading it to `deno` 0.35](https://github.com/chrmoritz/linuxbrew-core/commit/f55ac86a7fcce3da8316e10e55ec012bf93f3337)).

**Comment by iMichka** [comment]
We could do it, but not sure we want to do it.

I have been phasing Python 2 things out since beginning of December. We have around 49 formulae still using Python 2 right now. I touched around 64 formulae since the beginning: they were either deleted or migrated to Python 3.8.

I am fine to keep pypy around as long as upstream supports that 2.7 version. But most of the formulae we still have running are mostly dead/deprecated/unused, and were ment to be built with Python 2, not Pypy 2. I do not want to throw more energy at these. Also, using pypy may be surprising to some of our users.

Triaging these 64 formulae had a cost for me of around 50 to 60 hours of work. We need to end this Python 2 madness, the overall cost on the open source community over the last 11 years has been huge.

So sorry, but we won't do that.

**Comment by iMichka** [comment]
The list has been reduced to 36 formulae in linuxbrew-core (git grep "Due to Python 2"). The rest will slowly die with time, and the formulae are clearly identified and disabled on Linux. I'll just close this as we are not actively migrating the remaining ones.
