### ISSUE TITLE
Checksum mismatch on Par

### ISSUE THREAD

**Issue by glentner** [Homebrew/linuxbrew-core#19313]
- [ ] ran `brew update` and can still reproduce the problem? Yes
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I was installing `par` and it failed because of a mismatching checksum.

## What happened (include command output)
Indeed, the current tarball for Par 1.52 has the checksum found below.

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://web.archive.org/web/20190921042412/www.nicemice.net/par/Par152.tar.gz
==> Downloading from https://web.archive.org/web/20160312174248/http://www.nicemice.net/par/Par152.tar.gz
##O=#  #                                                                      
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 33dcdae905f4b4267b4dc1f3efb032d79705ca8d2122e17efdecfd8162067082
  Actual: 38b29555c75840e1a15aa61676966777adfd3d0746da9343c2676aa4e5be2b6e
 Archive: /home/glentner/.cache/Homebrew/downloads/fbda6ae01f7bb644cca3c80c211c6d19842eebf73fdecddd1fb9cfe432e67594--Par152.tar.gz
To retry an incomplete download, remove the file above.
  </pre>
</details>

## What you expected to happen

I expected the installation to succeed. Running `git blame` on `par.rb` shows it was changed on 2020-01-28; not sure why.

I edited the formula locally and things work fine now. Not sure why the formula changed. I was going to open a pull request but `brew audit` suggested an Issue instead because the version number didn't change.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install par`

**Comment by dawidd6** [comment]
Open the pull request in `Homebrew/homebrew-core` repository.

**Comment by issyl0** [comment]
This may have been happening since [October](https://github.com/Homebrew/homebrew-core/commit/3c5aea08e73a7655d42313795bf5be167af825a0) when the URL was changed but the checksum for the download wasn't updated. This software seems... somewhat unmaintained (the archive.org URL is interesting), but still gets a few downloads - on macOS at least. I reverted that commit locally and the checksum matches fine and the software continues to install on Linux. That might just be a coincidence though. :smile:

Normally in a checksum mismatch scenario, we'd ask the submitter to check with the upstream project that it was intentional so that we can rule out malicious activity. This is what the `brew audit` check exists for. However, it seems like one of our maintainers fixed the URLs in the commit linked above, so it's probably fine - but it's interesting that CI didn't pick it up at the time. :thinking:

Please do raise the checksum change PR in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) - the main macOS repo. If successful it'll get merged in here within a day. Thanks! :muscle:
