### ISSUE TITLE
gdal: qt, macOS is required

### ISSUE THREAD

**Issue by ptitle** [Homebrew/linuxbrew-core#19644]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/b55e54d4a129a27881bfa04a71cf845f
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to install gdal on RHEL 7.7

## What happened (include command output)

brew install gdal

<details>
  <summary>Command output</summary>
  <pre>

  qt: macOS is required.
Error: An unsatisfied requirement failed this build.

  </pre>
</details>

## What you expected to happen

It seems odd that this would require macOS when this is a RHEL installation.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

@jonchang

**Comment by jonchang** [comment]
This is because poppler has a qt backend which requires python2. I did some research into this and Debian has split the poppler backends into separate packages, poppler-qt, poppler-glib, and poppler-cpp, which all install the appropriate headers in subdirectories of `$prefix/include/poppler`, which means we can't use the same approach to decouple this dependency in Homebrew without some work.

I don't know what it would take to build qt using python3 (my Linux test machine ran out of disk space compiling it). I'll try again later this week.

**Comment by Char-Aznable** [comment]
I hit this problem as well. If we can do away without installing QtWebEngine then we can use python3 to build qt. See http://www.linuxfromscratch.org/blfs/view/svn/x/qt5.html

**Comment by jonchang** [comment]
This is being worked on here: https://github.com/Homebrew/linuxbrew-core/pull/19595

**Comment by iMichka** [comment]
qt is OK now. `gdal` fails to build from source though, see #19755

**Comment by jonchang** [comment]
This should be fixed. Thanks for the report Pascal.

**Comment by ptitle** [comment]
Thanks everyone!
