### ISSUE TITLE
gcc@10 for linuxbrew-core: Request for a bottle

### ISSUE THREAD

**Issue by asdetrefle** [Homebrew/linuxbrew-core#20355]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded? - no such formula

This is somehow related to [#54364](https://github.com/Homebrew/homebrew-core/pull/54364) which is blocked because all the softwares that depend on GCC need to be ported to GCC 10.

However it seems to me adding gcc@10 to linuxbrew-core should not be impacted and is straightforward because we use version tagged gcc@X. The versionless gcc is still pointing to gcc@5 in linuxbrew-core.

**Comment by iMichka** [comment]
As long as there is no gcc 10 in the Mac repo, we won't have a gcc 10 formula in the linux repo. Both repos are due to be merged soon, so we can't have too much differences between both to ease the merge.

I started to work on making changes to our gcc logic though in this PR: #20241
This is ongoing work but may take a little bit of time. So all this will be ready when we have solved the remaining issues.

Help is welcome to fix the build issues we are seeing, or the issues that have appeared in #20241.
