### ISSUE TITLE
suggest guidance in README.md on installation of `linuxbrew-wrapper` on debian/ubuntu

### ISSUE THREAD

**Issue by mcarifio** [Homebrew/linuxbrew-core#20734]
I installed linuxbrew yesterday (07/11/20) via `sudo apt install linuxbrew-wrapper` instead of shelling a script as directed by the README.md. I ended up with:

```bash
$ dpkg --list|grep linuxbrew
ii  linuxbrew-wrapper                                           20180923-1                               all          Homebrew package manager for Linux

$p type brew
brew is /usr/bin/brew

$ brew --version
Homebrew 2.4.5
Homebrew/linuxbrew-core (git revision 065ca4; last commit 2020-07-12)
```

The argument in favor of using a platform package manager, e.g. `apt` is that version updates are easier. The argument against is that some packages grow old. If you have a recommendation about which path to prefer (script or apt/dnf/whatever), please say so in the README.md file. If you advocate the script route, is there a `brew update` command that will update itself?

Ty

**Comment by tani** [comment]
Please don't missed that `linuxbrew-wrapper` is not same as Linuxbrew itself. In my memory, the wrapper is maintained by downstream developers.
If the wrapper application was implemented to download brew command from GitHub, as same as script route you said, there is no matter which you use. If not, you can request something to downstream developers.

The linuxbrew-core maintainers only supports the installtion via the script route. The wrapper script maintainers also only supports the wrapper script. I mean that your issue is depends on whom each users follows.

I'm curious that mention the other softwares in README. For example, Python's README do not mentioned about pyenv, pipenv, rbenv etc.

brew is updated itself automatically, I guess.

**Comment by iMichka** [comment]
As said above; this is a downstream wrapper.

>  For example, Python's README do not mentioned about pyenv, pipenv, rbenv etc.

Good point. And we will follow the same; we will not mention each tool/library/wrapper using linuxbrew.

We recommend using the instructions in there: https://brew.sh
But of course the `linuxbrew-wrapper` is probably fine and installs brew too. If you have questions about linuxbrew-wrapper, you should ask the maintainers of that tool.
