### ISSUE TITLE
Installing gnutls via Homebrew disables functionality of apps that are relying on it

### ISSUE THREAD

**Issue by alexanderadam** [Homebrew/linuxbrew-core#21332]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

[Running discord from flatpak while gnutls from homebrew was installed](https://github.com/flathub/com.discordapp.Discord/issues/93#issuecomment-640167696).

## What happened (include command output)

It didn't work and I got some certificate errors (see [flatpak issue 93](https://github.com/flathub/com.discordapp.Discord/issues/93#issuecomment-640167696))
[Removing gnutls from homebrew fixes this issue](https://github.com/flathub/com.discordapp.Discord/issues/93#issuecomment-640167696) but I guess there's probably a better solution for this?

## What you expected to happen

running should work

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
$ brew install gnutls
$ flatpak install flathub com.discordapp.Discord
$ reboot
$ flatpak run com.discordapp.Discord
```

**Comment by iMichka** [comment]
If our packages have an impact on system tools or other libraries; the bug is in these libraries; not in ours.
IMHO the bug is in flatpack or discord, not in brew.

Of course a PR is welcome to improve gnutls, but in the long term that's not a real solution.

Flatpack and discord should rely on system libraries; not whatever library is first in the path. Or they should ship their own internal libraries if these are critical for them.

**Comment by alexanderadam** [comment]
Isn't homebrew still setting environment variables? And can't environment variables change the behaviour of the whole session? :thinking:

**Comment by iMichka** [comment]
We set some during builds; but that's transient and local to the current terminal window.

You can have brew in the PATH env variable; but external non-brew software should not rely on stuff in the PATH, because that's too fragile. You can also remove homebrew from your PATH if that is a concern.

I do not see how this is a brew bug? Or maybe I misunderstood the issue.
