### ISSUE TITLE
PHP 7.4: configure: error: DBA: Could not find necessary header file(s)

### ISSUE THREAD

**Issue by daniel-simplyphp** [Homebrew/linuxbrew-core#22144]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tired to Install php 7.4 and only this version is not working. PHP 7.2, 7.3 and 8.0 work.

I have uninstalled HomeBrew completely, deleted all cache, ran brew doctor. All the other PHP versions are working as they should but I just cannot get PHP 7.4 to load. 
I have looked into the issue and loaded other packages that others suggested and still errors out.

## What happened (include command output)
<details>
  <summary>Brew Config Output</summary>
  <pre>
HOMEBREW_VERSION: 2.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c5ef032e9fe3cb391744a6f046363f912cc5a814
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit zen
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.19.128-microsoft-standard x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A
  </pre>
</details>

<details>
  <summary>Command output</summary>
  <pre>

  Last 15 lines from /home/daniel/.cache/Homebrew/Logs/php@7.4/02.configure:
checking for ZLIB support... yes
checking for zlib >= 1.2.0.4... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZ2_bzerror in -lbz2... yes
checking whether to enable calendar conversion support... yes
checking whether to enable ctype functions... yes
checking for cURL support... yes
checking for libcurl >= 7.15.5... yes
checking for SSL support in libcurl... yes
checking for libcurl linked against old openssl... no
checking for curl_easy_perform in -lcurl... yes
checking for QDBM support... no
checking for GDBM support... no
configure: error: DBA: Could not find necessary header file(s).
  </pre>
</details>

## What you expected to happen

To Install 7.4

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install php@7.4

**Comment by danielnachun** [comment]
This is failing because this formula doesn't have the necessary fixes to build on Linux.  You'll notice that `php@7.3` and `php` (8.0 is the newest version) have some parts of the formula inside of `if OS.mac?` blocks which set options that are macOS or Linux-specific.  

The presence of the `if OS.mac?` means that the `php` formulae are currently divergent between `homebrew/core` and `linuxbrew/core`, as `if OS.mac?` isn't allowed in `homebrew/core` formulae.  Eventually someone will have to do the work of porting the Linux fixes to `hombrew/core`, but the `php` formulae are complex so it will take some time.  

If you're willing to try to submit a PR to fix this, you'd basically just want to compare `php@7.4` to `php@7.3` and find the differences where `if OS.mac?` is being used in `php@7.3` and change them for `php@7.4`.  Otherwise I'll put this on my do list - I prioritize trying to fix problems with the newest version of formula but I can usually get to these things in a few days.

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/72391 should resolve this, but I would need help testing this.

**Comment by SMillerDev** [comment]
PHP 7.4 is now bottled for linux

**Comment by danielnachun** [comment]
This should now be fixed.
