### ISSUE TITLE
lttng-ust: Request for a bottle

### ISSUE THREAD

**Issue by lexicol** [Homebrew/linuxbrew-core#22611]
### Please verify that you've done all of the following:

- [X] checked that there aren't other open issues for the same formula bottle request
- [X] verified that the formula does not have a `bottle` block
- [X] ran `brew install FORMULA` successfully

Required for https://github.com/Homebrew/linuxbrew-core/pull/22609

**Comment by danielnachun** [comment]
I tried to bottle this but it fails because there is no bottle block.  I tried to manually add the bottle block but the sha256sum I got in Docker didn't match what was built in CI. @Hombrew/linux how do we request bottles for formulae which have no existing bottle block.  `brew request-bottle --ignore-errors` doesn't ignore the `--keep-old` error unfortunately.

**Comment by lexicol** [comment]
- https://github.com/Homebrew/linuxbrew-core/commit/72007a953b8c3091ac68eeff242b93a0ac29c241
- https://github.com/Homebrew/linuxbrew-core/commit/85fcf288ec01514fd6743dfe7b35f0ef3943b0e8
- https://github.com/Homebrew/linuxbrew-core/commit/4f5021fec1cce8b0f1dafe67e69098f4bb5925e3

Thanks @iMichka !
